[package]
name = "lag-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.9.1"
packet = "0.1.4"
nannou = "0.18.1"
ekko = "0.7.2"